[package]
name = "diesel_cli"
version = "1.4.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Provides the CLI for the Diesel crate"
readme = "README.md"
documentation = "https://diesel.rs/guides/getting-started"
homepage = "https://diesel.rs"
repository = "https://github.com/diesel-rs/diesel"
keywords = ["diesel", "migrations", "cli"]
autotests = false
edition = "2018"

[[bin]]
name = "diesel"
path = "src/main.rs"
doc = false

[dependencies]
chrono ={git = "https://github.com/warriorsfly/chrono"}
clap = "2.27"
dotenv = "0.15"
heck = "0.3.1"
serde = { version = "1.0.0", features = ["derive"] }
tempfile = "3.0.0"
toml = "0.4.6"
url = { version = "2.1.0", optional = true }
barrel = { version = ">= 0.5.0", optional = true, features = ["diesel"] }
libsqlite3-sys = { version = ">=0.8.0, <0.19.0", optional = true, features = ["min_sqlite_version_3_7_16"] }

[dependencies.diesel]
version = "~2.0.0"
path = "../diesel"
default-features = false

[dependencies.migrations_internals]
version = "~1.4.0"
path = "../diesel_migrations/migrations_internals"

[dev-dependencies]
difference = "1.0"
tempfile = "3.0.0"
regex = "0.2"
url = { version = "2.1.0" }

[features]
default = ["postgres", "sqlite", "mysql"]
postgres = ["diesel/postgres", "url", "uses_information_schema"]
sqlite = ["diesel/sqlite"]
mysql = ["diesel/mysql", "url", "uses_information_schema"]
barrel-migrations = ["migrations_internals/barrel", "barrel"]
sqlite-bundled = ["sqlite", "libsqlite3-sys/bundled"]
uses_information_schema = []

[[test]]
name = "tests"
